/*
 * GENERATED by tools/coa_stat_header_bauen.py from mod-playerbots-coa.
 * Do not edit by hand - the next run overwrites it.
 *
 * Stat weights for gear selection, one set per CoA specialization.
 *
 * WHAT THIS FIXES: StatsWeightCalculator::GenerateBasicWeights is a chain of
 * if/else over class and Blizzard talent tab. CoA classes match no branch and
 * are left with the base weights alone - stamina 0.1, armor 0.001, bonus 1.0.
 * A bot then picks gear by the item's total value, so a healer happily takes
 * agility and a melee spec takes spell power.
 *
 * WHERE THE NUMBERS COME FROM:
 *
 *   the ORDER      Sidekick's per-spec PvE stat priority, taken as given. It
 *                  carries things that cannot be guessed - the Barbarian
 *                  scales on Agility rather than Strength, Voodoo on Spirit,
 *                  Shadowhunting on ranged attack power like a hunter.
 *   the MAGNITUDE  an assumption, calibrated against the nine base classes:
 *                  Hunter/Marksmanship, Priest/Holy and Warrior/Protection.
 *                  Not measured.
 *
 * So the relative ranking is sourced, the absolute scale is an educated guess.
 *
 * needsThrown is not a weight at all. It records that the class has an ability
 * whose EquippedItemSubClassMask allows thrown weapons only - Throw, which
 * thirteen CoA classes learn at level 1, and the whole Headhunting kit around
 * Impaling Spear. The factory never offers INVTYPE_THROWN for the ranged slot,
 * so those bots run with an empty belt and the spells are simply uncastable.
 * Specs that carry a bow there are excluded.
 */

#ifndef PLAYERBOTS_COASPECSTATWEIGHTS_H
#define PLAYERBOTS_COASPECSTATWEIGHTS_H

#include <cstdint>

#include "StatsCollector.h"

struct CoaStatWeight
{
    StatsType stat;
    float weight;
};

struct CoaSpecStats
{
    uint8_t classId;
    uint16_t specId;
    char const* specName;
    char const* shape;              // for traceability only
    char const* weapon;             // twoHand, oneHand, dualWield, shield,
                                    // ranged, caster, any
    bool needsThrown;               // a rotation spell requires a thrown weapon
    CoaStatWeight const* weights;
    uint8_t count;
};

// Barbarian / Brutality (physisch_nah)
static constexpr CoaStatWeight CoaStats_12_2[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_ARMOR_PENETRATION, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Barbarian / Ancestry (physisch_nah)
static constexpr CoaStatWeight CoaStats_12_3[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_AGILITY, 2.04f }, { STATS_TYPE_HASTE, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_SPIRIT, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Barbarian / Headhunting (physisch_fern)
static constexpr CoaStatWeight CoaStats_12_1[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_ARMOR_PENETRATION, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Witch Doctor / Shadowhunting (physisch_fern)
static constexpr CoaStatWeight CoaStats_13_4[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_ATTACK_POWER, 2.3f }, { STATS_TYPE_CRIT, 2.08f }, { STATS_TYPE_AGILITY, 1.87f }, { STATS_TYPE_INTELLECT, 1.65f }, { STATS_TYPE_SPELL_POWER, 1.43f }, { STATS_TYPE_HIT, 1.22f }, { STATS_TYPE_HASTE, 1.0f } };
// Witch Doctor / Brewing (heilung)
static constexpr CoaStatWeight CoaStats_13_6[] = { { STATS_TYPE_SPIRIT, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_SPELL_POWER, 0.88f }, { STATS_TYPE_CRIT, 0.75f }, { STATS_TYPE_HASTE, 0.62f }, { STATS_TYPE_INTELLECT, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Witch Doctor / Voodoo (zauber)
static constexpr CoaStatWeight CoaStats_13_5[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPIRIT, 1.58f }, { STATS_TYPE_SPELL_POWER, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Felsworn / Slayer (physisch_nah)
static constexpr CoaStatWeight CoaStats_14_8[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_HASTE, 1.26f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Felsworn / Infernal (zauber)
static constexpr CoaStatWeight CoaStats_14_7[] = { { STATS_TYPE_SPIRIT, 1.8f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_INTELLECT, 1.25f }, { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Felsworn / Tyrant (tank)
static constexpr CoaStatWeight CoaStats_14_9[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_HIT, 1.6f }, { STATS_TYPE_EXPERTISE, 1.45f }, { STATS_TYPE_AGILITY, 1.3f }, { STATS_TYPE_ARMOR_PENETRATION, 1.15f }, { STATS_TYPE_CRIT, 1.0f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_HASTE, 0.85f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Witch Hunter / Boltslinger (physisch_fern)
static constexpr CoaStatWeight CoaStats_15_10[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Witch Hunter / Black Knight (tank)
static constexpr CoaStatWeight CoaStats_15_97[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_HIT, 1.6f }, { STATS_TYPE_EXPERTISE, 1.45f }, { STATS_TYPE_AGILITY, 1.3f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_CRIT, 0.85f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Witch Hunter / Houndmaster (physisch_fern)
static constexpr CoaStatWeight CoaStats_15_11[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.08f }, { STATS_TYPE_AGILITY, 1.87f }, { STATS_TYPE_INTELLECT, 1.65f }, { STATS_TYPE_SPELL_POWER, 1.43f }, { STATS_TYPE_CRIT, 1.22f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Witch Hunter / Inquisition (physisch_nah)
static constexpr CoaStatWeight CoaStats_15_12[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_SPELL_POWER, 1.78f }, { STATS_TYPE_AGILITY, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Stormbringer / Lightning (zauber)
static constexpr CoaStatWeight CoaStats_16_15[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_INTELLECT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Stormbringer / Maelstrom (zauber)
static constexpr CoaStatWeight CoaStats_16_14[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_INTELLECT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Stormbringer / Wind (zauber)
static constexpr CoaStatWeight CoaStats_16_13[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_INTELLECT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Knight of Xoroth / War (physisch_nah)
static constexpr CoaStatWeight CoaStats_17_18[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_STRENGTH, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Knight of Xoroth / Defiance (tank)
static constexpr CoaStatWeight CoaStats_17_17[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_STRENGTH, 0.85f }, { STATS_TYPE_ARMOR, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f } };
// Knight of Xoroth / Hellfire (zauber)
static constexpr CoaStatWeight CoaStats_17_16[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_STRENGTH, 1.36f }, { STATS_TYPE_CRIT, 1.14f }, { STATS_TYPE_HASTE, 0.92f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Guardian / Gladiator (physisch_nah)
static constexpr CoaStatWeight CoaStats_18_19[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.08f }, { STATS_TYPE_STRENGTH, 1.87f }, { STATS_TYPE_AGILITY, 1.65f }, { STATS_TYPE_ARMOR_PENETRATION, 1.43f }, { STATS_TYPE_CRIT, 1.22f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Guardian / Inspiration (physisch_nah)
static constexpr CoaStatWeight CoaStats_18_20[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.08f }, { STATS_TYPE_STRENGTH, 1.87f }, { STATS_TYPE_SPIRIT, 1.65f }, { STATS_TYPE_CRIT, 1.43f }, { STATS_TYPE_HASTE, 1.22f }, { STATS_TYPE_STAMINA, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Guardian / Vanguard (tank)
static constexpr CoaStatWeight CoaStats_18_21[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_EXPERTISE, 1.45f }, { STATS_TYPE_BLOCK_RATING, 1.15f }, { STATS_TYPE_STRENGTH, 1.0f }, { STATS_TYPE_ARMOR, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f } };
// Templar / Crusader (physisch_nah)
static constexpr CoaStatWeight CoaStats_19_24[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.08f }, { STATS_TYPE_AGILITY, 1.87f }, { STATS_TYPE_CRIT, 1.65f }, { STATS_TYPE_HASTE, 1.43f }, { STATS_TYPE_ARMOR_PENETRATION, 1.22f }, { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Templar / Oathkeeper (tank)
static constexpr CoaStatWeight CoaStats_19_22[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_HIT, 1.6f }, { STATS_TYPE_EXPERTISE, 1.45f }, { STATS_TYPE_AGILITY, 1.3f }, { STATS_TYPE_CRIT, 1.0f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_HASTE, 0.85f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Templar / Zealot (physisch_nah)
static constexpr CoaStatWeight CoaStats_19_23[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_ATTACK_POWER, 2.3f }, { STATS_TYPE_CRIT, 1.87f }, { STATS_TYPE_SPELL_POWER, 1.43f }, { STATS_TYPE_EXPERTISE, 1.0f } };
// Bloodmage / Sanguine (zauber)
static constexpr CoaStatWeight CoaStats_20_26[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_HASTE, 1.36f }, { STATS_TYPE_CRIT, 1.14f }, { STATS_TYPE_STAMINA, 0.92f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Bloodmage / Accursed (physisch_nah)
static constexpr CoaStatWeight CoaStats_20_27[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Bloodmage / Eternal (tank)
static constexpr CoaStatWeight CoaStats_20_99[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_EXPERTISE, 1.24f }, { STATS_TYPE_ARMOR, 1.06f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_AGILITY, 0.88f }, { STATS_TYPE_CRIT, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f } };
// Bloodmage / Fleshweaver (heilung)
static constexpr CoaStatWeight CoaStats_20_25[] = { { STATS_TYPE_SPELL_POWER, 1.8f }, { STATS_TYPE_SPIRIT, 1.58f }, { STATS_TYPE_STAMINA, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Ranger / Archery (physisch_fern)
static constexpr CoaStatWeight CoaStats_21_28[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_AGILITY, 1.97f }, { STATS_TYPE_CRIT, 1.65f }, { STATS_TYPE_ARMOR_PENETRATION, 1.32f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Ranger / Brigand (physisch_nah)
static constexpr CoaStatWeight CoaStats_21_30[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Ranger / Farstrider (physisch_fern)
static constexpr CoaStatWeight CoaStats_21_29[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_AGILITY, 1.97f }, { STATS_TYPE_CRIT, 1.65f }, { STATS_TYPE_HASTE, 1.32f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Chronomancer / Infinite (zauber)
static constexpr CoaStatWeight CoaStats_22_32[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_INTELLECT, 1.36f }, { STATS_TYPE_CRIT, 1.14f }, { STATS_TYPE_SPIRIT, 0.92f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Chronomancer / Artificer (zauber)
static constexpr CoaStatWeight CoaStats_22_33[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_PENETRATION, 1.62f }, { STATS_TYPE_SPIRIT, 1.43f }, { STATS_TYPE_CRIT, 1.25f }, { STATS_TYPE_HASTE, 1.07f }, { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Chronomancer / Time (heilung)
static constexpr CoaStatWeight CoaStats_22_31[] = { { STATS_TYPE_SPIRIT, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_SPELL_POWER, 0.9f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_HASTE, 0.8f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_CRIT, 0.6f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Necromancer / Animation (zauber)
static constexpr CoaStatWeight CoaStats_23_35[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.52f }, { STATS_TYPE_HASTE, 1.25f }, { STATS_TYPE_INTELLECT, 0.97f }, { STATS_TYPE_CRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Necromancer / Death (zauber)
static constexpr CoaStatWeight CoaStats_23_34[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_HASTE, 1.58f }, { STATS_TYPE_SPELL_POWER, 1.36f }, { STATS_TYPE_CRIT, 1.14f }, { STATS_TYPE_INTELLECT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Necromancer / Rime (zauber)
static constexpr CoaStatWeight CoaStats_23_36[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_INTELLECT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Pyromancer / Draconic (zauber)
static constexpr CoaStatWeight CoaStats_24_39[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_INTELLECT, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_STAMINA, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Pyromancer / Flameweaving (heilung)
static constexpr CoaStatWeight CoaStats_24_37[] = { { STATS_TYPE_SPIRIT, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_INTELLECT, 0.88f }, { STATS_TYPE_CRIT, 0.75f }, { STATS_TYPE_SPELL_POWER, 0.62f }, { STATS_TYPE_HASTE, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Pyromancer / Incineration (zauber)
static constexpr CoaStatWeight CoaStats_24_38[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_INTELLECT, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Cultist / Godblade (physisch_nah)
static constexpr CoaStatWeight CoaStats_25_42[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_STRENGTH, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Cultist / Corruption (zauber)
static constexpr CoaStatWeight CoaStats_25_41[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_INTELLECT, 1.36f }, { STATS_TYPE_CRIT, 1.14f }, { STATS_TYPE_HASTE, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Cultist / Dreadnought (tank)
static constexpr CoaStatWeight CoaStats_25_96[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_STRENGTH, 1.06f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_ARMOR, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f } };
// Cultist / Heretic (heilung)
static constexpr CoaStatWeight CoaStats_25_40[] = { { STATS_TYPE_CRIT, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_SPELL_POWER, 0.8f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_SPIRIT, 0.6f }, { STATS_TYPE_STAMINA, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Starcaller / Sentinel (zauber)
static constexpr CoaStatWeight CoaStats_26_44[] = { { STATS_TYPE_INTELLECT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_HIT, 0.92f }, { STATS_TYPE_AGILITY, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Starcaller / Moon Guard (tank)
static constexpr CoaStatWeight CoaStats_26_100[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_EXPERTISE, 1.38f }, { STATS_TYPE_BLOCK_RATING, 1.04f }, { STATS_TYPE_AGILITY, 0.93f }, { STATS_TYPE_INTELLECT, 0.81f }, { STATS_TYPE_CRIT, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Starcaller / Moon Priest (heilung)
static constexpr CoaStatWeight CoaStats_26_43[] = { { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_HASTE, 0.88f }, { STATS_TYPE_CRIT, 0.75f }, { STATS_TYPE_INTELLECT, 0.62f }, { STATS_TYPE_SPIRIT, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Starcaller / Warden (physisch_nah)
static constexpr CoaStatWeight CoaStats_26_45[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_SPELL_POWER, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Sun Cleric / Piety (zauber)
static constexpr CoaStatWeight CoaStats_27_46[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_CRIT, 1.36f }, { STATS_TYPE_HASTE, 1.14f }, { STATS_TYPE_INTELLECT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Sun Cleric / Blessings (heilung)
static constexpr CoaStatWeight CoaStats_27_98[] = { { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_HASTE, 0.9f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_CRIT, 0.8f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_SPIRIT, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Sun Cleric / Seraphim (tank)
static constexpr CoaStatWeight CoaStats_27_48[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_STRENGTH, 1.6f }, { STATS_TYPE_HIT, 1.42f }, { STATS_TYPE_SPELL_POWER, 1.24f }, { STATS_TYPE_ATTACK_POWER, 1.06f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_CRIT, 0.88f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Sun Cleric / Valkyrie (physisch_nah)
static constexpr CoaStatWeight CoaStats_27_47[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_STRENGTH, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_HASTE, 1.26f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Tinker / Demolition (physisch_fern)
static constexpr CoaStatWeight CoaStats_28_49[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_CRIT, 2.08f }, { STATS_TYPE_HASTE, 1.87f }, { STATS_TYPE_AGILITY, 1.65f }, { STATS_TYPE_ATTACK_POWER, 1.43f }, { STATS_TYPE_SPELL_POWER, 1.22f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f } };
// Tinker / Invention (heilung)
static constexpr CoaStatWeight CoaStats_28_51[] = { { STATS_TYPE_SPELL_POWER, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_INTELLECT, 0.9f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_SPIRIT, 0.8f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_CRIT, 0.6f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Tinker / Mechanics (physisch_fern)
static constexpr CoaStatWeight CoaStats_28_50[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.08f }, { STATS_TYPE_AGILITY, 1.87f }, { STATS_TYPE_ATTACK_POWER, 1.65f }, { STATS_TYPE_CRIT, 1.43f }, { STATS_TYPE_HASTE, 1.22f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f } };
// Venomancer / Rot (zauber)
static constexpr CoaStatWeight CoaStats_29_54[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_HASTE, 1.58f }, { STATS_TYPE_SPELL_POWER, 1.36f }, { STATS_TYPE_INTELLECT, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Venomancer / Fortitude (tank)
static constexpr CoaStatWeight CoaStats_29_52[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_AGILITY, 1.6f }, { STATS_TYPE_CRIT, 1.34f }, { STATS_TYPE_HASTE, 1.21f }, { STATS_TYPE_ATTACK_POWER, 1.09f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_ARMOR, 0.83f }, { STATS_TYPE_INTELLECT, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f } };
// Venomancer / Stalking (zauber)
static constexpr CoaStatWeight CoaStats_29_53[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.62f }, { STATS_TYPE_INTELLECT, 1.43f }, { STATS_TYPE_HASTE, 1.25f }, { STATS_TYPE_CRIT, 1.07f }, { STATS_TYPE_EXPERTISE, 0.88f }, { STATS_TYPE_ARMOR_PENETRATION, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Venomancer / Vizier (heilung)
static constexpr CoaStatWeight CoaStats_29_101[] = { { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_HEAL_POWER, 1.0f }, { STATS_TYPE_SPELL_POWER, 0.9f }, { STATS_TYPE_MANA_REGENERATION, 0.9f }, { STATS_TYPE_INTELLECT, 0.8f }, { STATS_TYPE_SPIRIT, 0.7f }, { STATS_TYPE_CRIT, 0.6f }, { STATS_TYPE_STAMINA, 0.5f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Reaper / Harvest (physisch_nah)
static constexpr CoaStatWeight CoaStats_30_56[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_STRENGTH, 1.78f }, { STATS_TYPE_ARMOR_PENETRATION, 1.52f }, { STATS_TYPE_CRIT, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Reaper / Domination (tank)
static constexpr CoaStatWeight CoaStats_30_57[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_HIT, 1.6f }, { STATS_TYPE_EXPERTISE, 1.42f }, { STATS_TYPE_STRENGTH, 1.06f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_CRIT, 0.88f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Reaper / Soul (physisch_nah)
static constexpr CoaStatWeight CoaStats_30_55[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_AGILITY, 2.04f }, { STATS_TYPE_ATTACK_POWER, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_HASTE, 1.26f }, { STATS_TYPE_INTELLECT, 1.0f } };
// Primalist / Wildwalker (physisch_nah)
static constexpr CoaStatWeight CoaStats_31_59[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_STRENGTH, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_ARMOR_PENETRATION, 1.26f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Primalist / Geomancy (zauber)
static constexpr CoaStatWeight CoaStats_31_95[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.62f }, { STATS_TYPE_INTELLECT, 1.43f }, { STATS_TYPE_HASTE, 1.25f }, { STATS_TYPE_CRIT, 1.07f }, { STATS_TYPE_STRENGTH, 0.88f }, { STATS_TYPE_ARMOR_PENETRATION, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Primalist / Grovekeeper (physisch_fern)
static constexpr CoaStatWeight CoaStats_31_58[] = { { STATS_TYPE_RANGED_DPS, 10.0f }, { STATS_TYPE_STRENGTH, 2.3f }, { STATS_TYPE_HASTE, 1.97f }, { STATS_TYPE_INTELLECT, 1.65f }, { STATS_TYPE_CRIT, 1.32f }, { STATS_TYPE_SPIRIT, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Primalist / Mountain King (tank)
static constexpr CoaStatWeight CoaStats_31_60[] = { { STATS_TYPE_STAMINA, 3.0f }, { STATS_TYPE_DEFENSE, 2.5f }, { STATS_TYPE_DODGE, 2.0f }, { STATS_TYPE_PARRY, 2.0f }, { STATS_TYPE_HIT, 1.6f }, { STATS_TYPE_EXPERTISE, 1.42f }, { STATS_TYPE_STRENGTH, 1.24f }, { STATS_TYPE_ARMOR_PENETRATION, 1.06f }, { STATS_TYPE_BLOCK_RATING, 1.0f }, { STATS_TYPE_CRIT, 0.88f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_BLOCK_VALUE, 0.5f }, { STATS_TYPE_ARMOR, 0.15f } };
// Runemaster / Glyphic (zauber)
static constexpr CoaStatWeight CoaStats_32_62[] = { { STATS_TYPE_HIT, 1.8f }, { STATS_TYPE_SPELL_POWER, 1.58f }, { STATS_TYPE_INTELLECT, 1.36f }, { STATS_TYPE_SPIRIT, 1.14f }, { STATS_TYPE_CRIT, 0.92f }, { STATS_TYPE_HASTE, 0.7f }, { STATS_TYPE_ATTACK_POWER, -1.0f } };
// Runemaster / Engravement (physisch_nah)
static constexpr CoaStatWeight CoaStats_32_61[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 1.97f }, { STATS_TYPE_AGILITY, 1.65f }, { STATS_TYPE_CRIT, 1.32f }, { STATS_TYPE_HASTE, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };
// Runemaster / Riftblade (physisch_nah)
static constexpr CoaStatWeight CoaStats_32_63[] = { { STATS_TYPE_MELEE_DPS, 7.5f }, { STATS_TYPE_HIT, 2.3f }, { STATS_TYPE_EXPERTISE, 2.04f }, { STATS_TYPE_AGILITY, 1.78f }, { STATS_TYPE_CRIT, 1.52f }, { STATS_TYPE_HASTE, 1.26f }, { STATS_TYPE_ARMOR_PENETRATION, 1.0f }, { STATS_TYPE_ATTACK_POWER, 1.0f } };

static constexpr CoaSpecStats CoaSpecStatsTable[] =
{
    { 12,   2, "Brutality", "physisch_nah", "any", true, CoaStats_12_2, 8 },
    { 12,   3, "Ancestry", "physisch_nah", "shield", true, CoaStats_12_3, 8 },
    { 12,   1, "Headhunting", "physisch_fern", "twoHand", true, CoaStats_12_1, 8 },
    { 13,   4, "Shadowhunting", "physisch_fern", "dualWield", true, CoaStats_13_4, 8 },
    { 13,   6, "Brewing", "heilung", "caster", true, CoaStats_13_6, 8 },
    { 13,   5, "Voodoo", "zauber", "caster", true, CoaStats_13_5, 7 },
    { 14,   8, "Slayer", "physisch_nah", "dualWield", true, CoaStats_14_8, 8 },
    { 14,   7, "Infernal", "zauber", "caster", true, CoaStats_14_7, 6 },
    { 14,   9, "Tyrant", "tank", "twoHand", true, CoaStats_14_9, 13 },
    { 15,  10, "Boltslinger", "physisch_fern", "any", false, CoaStats_15_10, 8 },
    { 15,  97, "Black Knight", "tank", "twoHand", false, CoaStats_15_97, 13 },
    { 15,  11, "Houndmaster", "physisch_fern", "ranged", false, CoaStats_15_11, 9 },
    { 15,  12, "Inquisition", "physisch_nah", "dualWield", false, CoaStats_15_12, 8 },
    { 16,  15, "Lightning", "zauber", "caster", false, CoaStats_16_15, 7 },
    { 16,  14, "Maelstrom", "zauber", "caster", false, CoaStats_16_14, 7 },
    { 16,  13, "Wind", "zauber", "caster", false, CoaStats_16_13, 7 },
    { 17,  18, "War", "physisch_nah", "twoHand", true, CoaStats_17_18, 8 },
    { 17,  17, "Defiance", "tank", "shield", true, CoaStats_17_17, 8 },
    { 17,  16, "Hellfire", "zauber", "twoHand", true, CoaStats_17_16, 7 },
    { 18,  19, "Gladiator", "physisch_nah", "shield", true, CoaStats_18_19, 9 },
    { 18,  20, "Inspiration", "physisch_nah", "shield", true, CoaStats_18_20, 9 },
    { 18,  21, "Vanguard", "tank", "shield", true, CoaStats_18_21, 9 },
    { 19,  24, "Crusader", "physisch_nah", "twoHand", true, CoaStats_19_24, 9 },
    { 19,  22, "Oathkeeper", "tank", "twoHand", true, CoaStats_19_22, 13 },
    { 19,  23, "Zealot", "physisch_nah", "dualWield", true, CoaStats_19_23, 5 },
    { 20,  26, "Sanguine", "zauber", "caster", true, CoaStats_20_26, 7 },
    { 20,  27, "Accursed", "physisch_nah", "twoHand", true, CoaStats_20_27, 8 },
    { 20,  99, "Eternal", "tank", "any", true, CoaStats_20_99, 10 },
    { 20,  25, "Fleshweaver", "heilung", "any", true, CoaStats_20_25, 7 },
    { 21,  28, "Archery", "physisch_fern", "ranged", false, CoaStats_21_28, 7 },
    { 21,  30, "Brigand", "physisch_nah", "any", true, CoaStats_21_30, 8 },
    { 21,  29, "Farstrider", "physisch_fern", "ranged", false, CoaStats_21_29, 7 },
    { 22,  32, "Infinite", "zauber", "caster", false, CoaStats_22_32, 7 },
    { 22,  33, "Artificer", "zauber", "caster", false, CoaStats_22_33, 8 },
    { 22,  31, "Time", "heilung", "caster", false, CoaStats_22_31, 8 },
    { 23,  35, "Animation", "zauber", "any", false, CoaStats_23_35, 6 },
    { 23,  34, "Death", "zauber", "caster", false, CoaStats_23_34, 7 },
    { 23,  36, "Rime", "zauber", "caster", false, CoaStats_23_36, 7 },
    { 24,  39, "Draconic", "zauber", "caster", false, CoaStats_24_39, 7 },
    { 24,  37, "Flameweaving", "heilung", "caster", false, CoaStats_24_37, 8 },
    { 24,  38, "Incineration", "zauber", "caster", false, CoaStats_24_38, 7 },
    { 25,  42, "Godblade", "physisch_nah", "twoHand", true, CoaStats_25_42, 8 },
    { 25,  41, "Corruption", "zauber", "caster", true, CoaStats_25_41, 7 },
    { 25,  96, "Dreadnought", "tank", "shield", true, CoaStats_25_96, 8 },
    { 25,  40, "Heretic", "heilung", "twoHand", true, CoaStats_25_40, 8 },
    { 26,  44, "Sentinel", "zauber", "ranged", false, CoaStats_26_44, 7 },
    { 26, 100, "Moon Guard", "tank", "shield", false, CoaStats_26_100, 11 },
    { 26,  43, "Moon Priest", "heilung", "twoHand", false, CoaStats_26_43, 8 },
    { 26,  45, "Warden", "physisch_nah", "caster", false, CoaStats_26_45, 8 },
    { 27,  46, "Piety", "zauber", "caster", false, CoaStats_27_46, 7 },
    { 27,  98, "Blessings", "heilung", "any", false, CoaStats_27_98, 8 },
    { 27,  48, "Seraphim", "tank", "shield", false, CoaStats_27_48, 13 },
    { 27,  47, "Valkyrie", "physisch_nah", "dualWield", false, CoaStats_27_47, 8 },
    { 28,  49, "Demolition", "physisch_fern", "ranged", false, CoaStats_28_49, 8 },
    { 28,  51, "Invention", "heilung", "ranged", false, CoaStats_28_51, 8 },
    { 28,  50, "Mechanics", "physisch_fern", "caster", false, CoaStats_28_50, 8 },
    { 29,  54, "Rot", "zauber", "caster", true, CoaStats_29_54, 7 },
    { 29,  52, "Fortitude", "tank", "caster", true, CoaStats_29_52, 12 },
    { 29,  53, "Stalking", "zauber", "caster", true, CoaStats_29_53, 8 },
    { 29, 101, "Vizier", "heilung", "caster", true, CoaStats_29_101, 9 },
    { 30,  56, "Harvest", "physisch_nah", "twoHand", true, CoaStats_30_56, 8 },
    { 30,  57, "Domination", "tank", "twoHand", true, CoaStats_30_57, 12 },
    { 30,  55, "Soul", "physisch_nah", "dualWield", true, CoaStats_30_55, 7 },
    { 31,  59, "Wildwalker", "physisch_nah", "twoHand", true, CoaStats_31_59, 8 },
    { 31,  95, "Geomancy", "zauber", "caster", true, CoaStats_31_95, 8 },
    { 31,  58, "Grovekeeper", "physisch_fern", "any", true, CoaStats_31_58, 7 },
    { 31,  60, "Mountain King", "tank", "dualWield", true, CoaStats_31_60, 13 },
    { 32,  62, "Glyphic", "zauber", "any", true, CoaStats_32_62, 7 },
    { 32,  61, "Engravement", "physisch_nah", "dualWield", true, CoaStats_32_61, 7 },
    { 32,  63, "Riftblade", "physisch_nah", "twoHand", true, CoaStats_32_63, 8 },
};

// The weights for a spec, or nullptr when we have none.
static inline CoaSpecStats const* GetCoaSpecStats(uint8_t classId, uint16_t specId)
{
    for (CoaSpecStats const& e : CoaSpecStatsTable)
        if (e.classId == classId && e.specId == specId)
            return &e;

    return nullptr;
}

// The default of a class: its first row, for a bot without a specialization.
static inline CoaSpecStats const* GetCoaDefaultSpecStats(uint8_t classId)
{
    for (CoaSpecStats const& e : CoaSpecStatsTable)
        if (e.classId == classId)
            return &e;

    return nullptr;
}

#endif
