/*
 * GENERATED by tools/coa_spec_header_bauen.py from mod-playerbots-coa.
 * Do not edit by hand - the next run overwrites it.
 *
 * One row per CoA specialization: which role it plays, where it stands, and
 * which rotation it runs. The source is the same one the rotations and the
 * seeded database rows come from, so core and database cannot drift apart.
 *
 * Why this lives in the core rather than in the database: AiFactory only knows
 * the nine base classes, and PlayerbotFactory::Randomize falls back to exactly
 * that point through ResetStrategies(). Seeded rows are gone after that, code
 * is not.
 *
 * The first row of a class is its default - the spec a bot gets when none has
 * been chosen yet.
 */

#ifndef PLAYERBOTS_COASPECSTRATEGIES_H
#define PLAYERBOTS_COASPECSTRATEGIES_H

#include <cstdint>

enum class CoaSpecRole : uint8_t
{
    Dps,
    Tank,
    Heal,
};

struct CoaSpecStrategy
{
    uint8_t classId;
    uint16_t specId;
    char const* specName;
    CoaSpecRole role;
    char const* position;      // "close" or "ranged"
    char const* combat;        // custom::<class>-<spec>
    char const* nonCombat;     // custom::<class>-<spec>-nc, otherwise nullptr
    bool support;              // a damage dealer that also carries the group
};

static constexpr CoaSpecStrategy CoaSpecStrategies[] =
{
    // Barbarian
    { 12,   2, "Brutality", CoaSpecRole::Dps, "close", "custom::barbarian-brutality", nullptr, false },  // default
    { 12,   3, "Ancestry", CoaSpecRole::Dps, "close", "custom::barbarian-ancestry", nullptr, true },
    { 12,   1, "Headhunting", CoaSpecRole::Dps, "ranged", "custom::barbarian-headhunting", nullptr, false },

    // Witch Doctor
    { 13,   4, "Shadowhunting", CoaSpecRole::Dps, "ranged", "custom::witch-doctor-shadowhunting", nullptr, false },  // default
    { 13,   6, "Brewing", CoaSpecRole::Heal, "ranged", "custom::witch-doctor-brewing", nullptr, false },
    { 13,   5, "Voodoo", CoaSpecRole::Dps, "ranged", "custom::witch-doctor-voodoo", nullptr, false },

    // Felsworn
    { 14,   8, "Slayer", CoaSpecRole::Dps, "close", "custom::felsworn-slayer", nullptr, false },  // default
    { 14,   7, "Infernal", CoaSpecRole::Dps, "ranged", "custom::felsworn-infernal", nullptr, false },
    { 14,   9, "Tyrant", CoaSpecRole::Tank, "close", "custom::felsworn-tyrant", nullptr, false },

    // Witch Hunter
    { 15,  10, "Boltslinger", CoaSpecRole::Dps, "ranged", "custom::witch-hunter-boltslinger", nullptr, false },  // default
    { 15,  97, "Black Knight", CoaSpecRole::Tank, "close", "custom::witch-hunter-black-knight", nullptr, false },
    { 15,  11, "Houndmaster", CoaSpecRole::Dps, "ranged", "custom::witch-hunter-houndmaster", nullptr, false },
    { 15,  12, "Inquisition", CoaSpecRole::Dps, "close", "custom::witch-hunter-inquisition", nullptr, false },

    // Stormbringer
    { 16,  15, "Lightning", CoaSpecRole::Dps, "ranged", "custom::stormbringer-lightning", nullptr, false },  // default
    { 16,  14, "Maelstrom", CoaSpecRole::Dps, "ranged", "custom::stormbringer-maelstrom", nullptr, false },
    { 16,  13, "Wind", CoaSpecRole::Dps, "ranged", "custom::stormbringer-wind", nullptr, true },

    // Knight of Xoroth
    { 17,  18, "War", CoaSpecRole::Dps, "close", "custom::knight-of-xoroth-war", nullptr, false },  // default
    { 17,  17, "Defiance", CoaSpecRole::Tank, "close", "custom::knight-of-xoroth-defiance", nullptr, false },
    { 17,  16, "Hellfire", CoaSpecRole::Dps, "close", "custom::knight-of-xoroth-hellfire", nullptr, false },

    // Guardian
    { 18,  19, "Gladiator", CoaSpecRole::Dps, "close", "custom::guardian-gladiator", nullptr, false },  // default
    { 18,  20, "Inspiration", CoaSpecRole::Dps, "close", "custom::guardian-inspiration", nullptr, true },
    { 18,  21, "Vanguard", CoaSpecRole::Tank, "close", "custom::guardian-vanguard", nullptr, false },

    // Templar
    { 19,  24, "Crusader", CoaSpecRole::Dps, "close", "custom::templar-crusader", nullptr, false },  // default
    { 19,  22, "Oathkeeper", CoaSpecRole::Tank, "close", "custom::templar-oathkeeper", nullptr, false },
    { 19,  23, "Zealot", CoaSpecRole::Dps, "close", "custom::templar-zealot", nullptr, false },

    // Bloodmage
    { 20,  26, "Sanguine", CoaSpecRole::Dps, "ranged", "custom::bloodmage-sanguine", nullptr, false },  // default
    { 20,  27, "Accursed", CoaSpecRole::Dps, "close", "custom::bloodmage-accursed", nullptr, false },
    { 20,  99, "Eternal", CoaSpecRole::Tank, "close", "custom::bloodmage-eternal", nullptr, false },
    { 20,  25, "Fleshweaver", CoaSpecRole::Heal, "ranged", "custom::bloodmage-fleshweaver", nullptr, true },

    // Ranger
    { 21,  28, "Archery", CoaSpecRole::Dps, "ranged", "custom::ranger-archery", nullptr, false },  // default
    { 21,  30, "Brigand", CoaSpecRole::Dps, "close", "custom::ranger-brigand", nullptr, false },
    { 21,  29, "Farstrider", CoaSpecRole::Dps, "ranged", "custom::ranger-farstrider", nullptr, true },

    // Chronomancer
    { 22,  32, "Infinite", CoaSpecRole::Dps, "ranged", "custom::chronomancer-infinite", nullptr, false },  // default
    { 22,  33, "Artificer", CoaSpecRole::Dps, "ranged", "custom::chronomancer-artificer", nullptr, false },
    { 22,  31, "Time", CoaSpecRole::Heal, "ranged", "custom::chronomancer-time", nullptr, false },

    // Necromancer
    { 23,  35, "Animation", CoaSpecRole::Dps, "ranged", "custom::necromancer-animation", nullptr, false },  // default
    { 23,  34, "Death", CoaSpecRole::Dps, "ranged", "custom::necromancer-death", nullptr, false },
    { 23,  36, "Rime", CoaSpecRole::Dps, "ranged", "custom::necromancer-rime", nullptr, false },

    // Pyromancer
    { 24,  39, "Draconic", CoaSpecRole::Dps, "ranged", "custom::pyromancer-draconic", nullptr, false },  // default
    { 24,  37, "Flameweaving", CoaSpecRole::Heal, "ranged", "custom::pyromancer-flameweaving", nullptr, false },
    { 24,  38, "Incineration", CoaSpecRole::Dps, "ranged", "custom::pyromancer-incineration", nullptr, false },

    // Cultist
    { 25,  42, "Godblade", CoaSpecRole::Dps, "close", "custom::cultist-godblade", nullptr, false },  // default
    { 25,  41, "Corruption", CoaSpecRole::Dps, "ranged", "custom::cultist-corruption", nullptr, false },
    { 25,  96, "Dreadnought", CoaSpecRole::Tank, "close", "custom::cultist-dreadnought", nullptr, false },
    { 25,  40, "Heretic", CoaSpecRole::Heal, "ranged", "custom::cultist-heretic", nullptr, false },

    // Starcaller
    { 26,  44, "Sentinel", CoaSpecRole::Dps, "ranged", "custom::starcaller-sentinel", nullptr, false },  // default
    { 26, 100, "Moon Guard", CoaSpecRole::Tank, "close", "custom::starcaller-moon-guard", nullptr, false },
    { 26,  43, "Moon Priest", CoaSpecRole::Heal, "ranged", "custom::starcaller-moon-priest", nullptr, false },
    { 26,  45, "Warden", CoaSpecRole::Dps, "close", "custom::starcaller-warden", nullptr, false },

    // Sun Cleric
    { 27,  46, "Piety", CoaSpecRole::Dps, "ranged", "custom::sun-cleric-piety", nullptr, false },  // default
    { 27,  98, "Blessings", CoaSpecRole::Heal, "ranged", "custom::sun-cleric-blessings", nullptr, false },
    { 27,  48, "Seraphim", CoaSpecRole::Tank, "close", "custom::sun-cleric-seraphim", nullptr, false },
    { 27,  47, "Valkyrie", CoaSpecRole::Dps, "close", "custom::sun-cleric-valkyrie", nullptr, false },

    // Tinker
    { 28,  49, "Demolition", CoaSpecRole::Dps, "ranged", "custom::tinker-demolition", "custom::tinker-nc", false },  // default
    { 28,  51, "Invention", CoaSpecRole::Heal, "ranged", "custom::tinker-invention", nullptr, false },
    { 28,  50, "Mechanics", CoaSpecRole::Dps, "ranged", "custom::tinker-mechanics", nullptr, false },

    // Venomancer
    { 29,  54, "Rot", CoaSpecRole::Dps, "ranged", "custom::venomancer-rot", nullptr, false },  // default
    { 29,  52, "Fortitude", CoaSpecRole::Tank, "close", "custom::venomancer-fortitude", nullptr, false },
    { 29,  53, "Stalking", CoaSpecRole::Dps, "close", "custom::venomancer-stalking", nullptr, false },
    { 29, 101, "Vizier", CoaSpecRole::Heal, "ranged", "custom::venomancer-vizier", nullptr, false },

    // Reaper
    { 30,  56, "Harvest", CoaSpecRole::Dps, "close", "custom::reaper-harvest", nullptr, false },  // default
    { 30,  57, "Domination", CoaSpecRole::Tank, "close", "custom::reaper-domination", nullptr, false },
    { 30,  55, "Soul", CoaSpecRole::Dps, "close", "custom::reaper-soul", nullptr, false },

    // Primalist
    { 31,  59, "Wildwalker", CoaSpecRole::Dps, "close", "custom::primalist-wildwalker", nullptr, false },  // default
    { 31,  95, "Geomancy", CoaSpecRole::Dps, "ranged", "custom::primalist-geomancy", nullptr, false },
    { 31,  58, "Grovekeeper", CoaSpecRole::Dps, "ranged", "custom::primalist-grovekeeper", nullptr, true },
    { 31,  60, "Mountain King", CoaSpecRole::Tank, "close", "custom::primalist-mountain-king", nullptr, false },

    // Runemaster
    { 32,  62, "Glyphic", CoaSpecRole::Dps, "ranged", "custom::runemaster-glyphic", nullptr, false },  // default
    { 32,  61, "Engravement", CoaSpecRole::Dps, "close", "custom::runemaster-engravement", nullptr, false },
    { 32,  63, "Riftblade", CoaSpecRole::Dps, "close", "custom::runemaster-riftblade", nullptr, false },
};

// The spec a bot actually plays. Returns nullptr for a class that is not a CoA
// class, and for a spec id we do not know.
static constexpr CoaSpecStrategy const* GetCoaSpecStrategy(uint8_t classId, uint16_t specId)
{
    for (CoaSpecStrategy const& e : CoaSpecStrategies)
        if (e.classId == classId && e.specId == specId)
            return &e;

    return nullptr;
}

// The default of a class: its first row. Used while a bot has no spec set yet.
static constexpr CoaSpecStrategy const* GetCoaDefaultSpecStrategy(uint8_t classId)
{
    for (CoaSpecStrategy const& e : CoaSpecStrategies)
        if (e.classId == classId)
            return &e;

    return nullptr;
}

#endif
